version = 1

[[annotations]]
path = ["cycle_p.h"]
precedence = "closest"
SPDX-FileCopyrightText = ["Copyright (c) 2003, 2007-14 Matteo Frigo",
                          "Copyright (c) 2003, 2007-14 Massachusetts Institute of Technology"]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["*.patch"]
precedence = "closest"
SPDX-FileCopyrightText = ["None"]
SPDX-License-Identifier = "CC0-1.0"