/* This file was generated by syncqt. */
#ifndef QT_QTWIDGETS_VERSION_H
#define QT_QTWIDGETS_VERSION_H

#define QTWIDGETS_VERSION_STR "6.2.11"

#define QTWIDGETS_VERSION 0x06020B

#endif // QT_QTWIDGETS_VERSION_H
