/* This file was generated by syncqt. */
#ifndef QT_QTWIDGETS_VERSION_H
#define QT_QTWIDGETS_VERSION_H

#define QTWIDGETS_VERSION_STR "6.2.12"

#define QTWIDGETS_VERSION 0x06020C

#endif // QT_QTWIDGETS_VERSION_H
