version = 1

[[annotations]]
path = ["module.mk", "rules.mk", "truetype.c", "ttdriver.c", "ttdriver.h", "ttgload.c",
        "ttgload.h", "ttinterp.c", "ttinterp.h", "ttobjs.c", "ttobjs.h", "ttpload.c", "ttpload.h"]
comment = "Copyright continuation line ignored by reuse for lack of word Copyright at start."
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 1996-2023 by David Turner, Robert Wilhelm, and Werner Lemberg."
SPDX-License-Identifier = "FTL OR GPL-2.0-only"

[[annotations]]
path = "tterrors.h"
comment = "Copyright continuation line ignored by reuse for lack of word Copyright at start."
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2001-2023 by David Turner, Robert Wilhelm, and Werner Lemberg."
SPDX-License-Identifier = "FTL OR GPL-2.0-only"

[[annotations]]
path = ["ttgxvar.c", "ttgxvar.h"]
comment = "Copyright continuation line ignored by reuse for lack of word Copyright at start."
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2004-2023 by David Turner, Robert Wilhelm, Werner Lemberg, and George Williams."
SPDX-License-Identifier = "FTL OR GPL-2.0-only"
