version = 1

[[annotations]]
path = ["valgrind_p.h", "callgrind_p.h"]
precedence = "closest"
SPDX-FileCopyrightText = ["Copyright (C) 2000-2017 Julian Seward",
        "Copyright (C) 2003-2017 Josef Weidendorfer."]
SPDX-License-Identifier = "BSD-4-Clause"