version = 1

[[annotations]]
path = ["**"]
precedence = "closest"
SPDX-FileCopyrightText = ["Copyright (C) 2001-2006 Bart Massey, Jamey Sharp, and Josh Triplett.",
    "Copyright (C) 2006 Peter Hutterer",
    "Copyright (C) 2013 Daniel Martin"]
SPDX-License-Identifier = "MIT"
