version = 1

[[annotations]]
path = ["*"]
precedence = "aggregate"
SPDX-License-Identifier = "FTL OR GPL-2.0-only"

[[annotations]]
path = ["module.mk", "psaux.c", "psobjs.c", "psobjs.h", "rules.mk"]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 1996-2023 by David Turner, Robert Wilhelm, and Werner Lemberg."
SPDX-License-Identifier = "FTL OR GPL-2.0-only"

[[annotations]]
path = ["psauxmod.c", "psauxmod.h", "t1decode.c", "t1decode.h"]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2000-2023 by David Turner, Robert Wilhelm, and Werner Lemberg."
SPDX-License-Identifier = "FTL OR GPL-2.0-only"

[[annotations]]
path = ["psauxerr.h"]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2001-2023 by David Turner, Robert Wilhelm, and Werner Lemberg."
SPDX-License-Identifier = "FTL OR GPL-2.0-only"

[[annotations]]
path = ["t1cmap.c", "t1cmap.h"]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2002-2023 by David Turner, Robert Wilhelm, and Werner Lemberg."
SPDX-License-Identifier = "FTL OR GPL-2.0-only"

[[annotations]]
path = ["afmparse.c", "afmparse.h", "psconv.c", "psconv.h"]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2006-2023 by David Turner, Robert Wilhelm, and Werner Lemberg."
SPDX-License-Identifier = "FTL OR GPL-2.0-only"

[[annotations]]
path = ["cffdecode.c", "cffdecode.h"]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2017-2023 by David Turner, Robert Wilhelm, and Werner Lemberg."
SPDX-License-Identifier = "FTL OR GPL-2.0-only"
