version = 1

[[annotations]]
path = ["bdf.h", "README", "bdferror.h"]
precedence = "closest"
SPDX-FileCopyrightText = ["Copyright (c) 2000 Computing Research Labs, New Mexico State University",
                          "Copyright (c) 2001-2014 Francesco Zappa Nardelli"]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["bdflib.c"]
comment = "Copyright continuation line ignored by reuse for lack of word Copyright at start."
precedence = "override"
SPDX-FileCopyrightText = ["Copyright (c) 2000 Computing Research Labs, New Mexico State University",
                          "Copyright (c) 2001-2014 Francesco Zappa Nardelli"]
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["rules.mk", "module.mk", "bdfdrivr.h", "bdfdrivr.c", "bdf.c"]
comment = "Copyright continuation line ignored by reuse for lack of word Copyright at start."
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2001-2014 Francesco Zappa Nardelli"
SPDX-License-Identifier = "MIT"
