version = 1

[[annotations]]
path = "PROBLEMS"
precedence = "override"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "FTL OR GPL-2.0-only"

[[annotations]]
path = "CHANGES"
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2000-2023 by David Turner, Robert Wilhelm, and Werner Lemberg."
SPDX-License-Identifier = "FTL OR GPL-2.0-only"

[[annotations]]
path = "CUSTOMIZE"
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2003-2023 by David Turner, Robert Wilhelm, and Werner Lemberg."
SPDX-License-Identifier = "FTL OR GPL-2.0-only"

[[annotations]]
path = "DEBUG"
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2002-2023 by David Turner, Robert Wilhelm, and Werner Lemberg."
SPDX-License-Identifier = "FTL OR GPL-2.0-only"

[[annotations]]
path = "TODO"
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2001-2023 by David Turner, Robert Wilhelm, and Werner Lemberg."
SPDX-License-Identifier = "FTL OR GPL-2.0-only"

[[annotations]]
path = "FTL.TXT"
precedence = "override"
SPDX-FileCopyrightText = "Copyright 1996-2002, 2006 by David Turner, Robert Wilhelm, and Werner Lemberg."
SPDX-License-Identifier = "FTL"

[[annotations]]
path = "GPLv2.TXT"
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 1989, 1991 Free Software Foundation, Inc."
SPDX-License-Identifier = "GPL-2.0-only"

[[annotations]]
path = "REUSE.toml"
comment = "The copyrights inside those files are not related to the file"
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2024 The Qt Company Ltd."
SPDX-License-Identifier = "BSD-3-Clause"
