version = 1

[[annotations]]
path = ["module.mk", "rules.mk", "t1afm.c", "t1afm.h", "t1driver.c", "t1driver.h", "t1gload.c", "t1gload.h",
        "t1load.c", "t1load.h", "t1objs.c", "t1objs.h", "t1parse.c", "t1parse.h", "t1tokens.h", "type1.c"]
comment = "Copyright continuation line ignored by reuse for lack of word Copyright at start."
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 1996-2023 by David Turner, Robert Wilhelm, and Werner Lemberg."
SPDX-License-Identifier = "FTL OR GPL-2.0-only"

[[annotations]]
path = "t1errors.h"
comment = "Copyright continuation line ignored by reuse for lack of word Copyright at start."
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2001-2023 by David Turner, Robert Wilhelm, and Werner Lemberg."
SPDX-License-Identifier = "FTL OR GPL-2.0-only"
