version = 1

[[annotations]]
path = "winfnt.c"
comment = "Copyright continuation line ignored by reuse for lack of word Copyright at start."
precedence = "override"
SPDX-FileCopyrightText = ["Copyright (c) 2001, 2012 David Turner, Robert Wilhelm, and Werner Lemberg",
                          "Copyright 2003 Huw D M Davies for Codeweavers",
                          "Copyright 2007 Dmitry Timoshkov for Codeweavers"]
SPDX-License-Identifier = "FTL OR GPL-2.0-only"

[[annotations]]
path = "winfnt.h"
comment = "Copyright continuation line ignored by reuse for lack of word Copyright at start."
precedence = "override"
SPDX-FileCopyrightText = ["Copyright (c) 2001, 2012 David Turner, Robert Wilhelm, and Werner Lemberg",
                          "Copyright 2007 Dmitry Timoshkov for Codeweavers"]
SPDX-License-Identifier = "FTL OR GPL-2.0-only"

[[annotations]]
path = ["module.mk", "fnterrs.h", "rules.mk"]
comment = "Copyright continuation line ignored by reuse for lack of word Copyright at start."
precedence = "override"
SPDX-FileCopyrightText = "Copyright (c) 2001, 2012 David Turner, Robert Wilhelm, and Werner Lemberg"
SPDX-License-Identifier = "FTL OR GPL-2.0-only"
