
version = 1

[[annotations]]
path = ["**"]
precedence = "closest"
SPDX-FileCopyrightText = ["Copyright 2014-2016 The Chromium Authors. All rights reserved."]
SPDX-License-Identifier = "BSD-3-Clause"

[[annotations]]
path = ["psl_data.cpp"]
precedence = "closest"
SPDX-FileCopyrightText = ["The list was originally provided by Jo Hermans <jo.hermans@gmail.com>.\nIt is now maintained on github (https://github.com/publicsuffix/list)."]
SPDX-License-Identifier = "MPL-2.0"

