version = 1


[[annotations]]
path = ["perf_event_p.h"]
precedence = "closest"
SPDX-FileCopyrightText = ["Copyright (C) 2008-2009, Thomas Gleixner <tglx@linutronix.de>",
        "Copyright (C) 2008-2011, Red Hat, Inc., Ingo Molnar",
        "Copyright (C) 2008-2011, Red Hat, Inc., Peter Zijlstra"]
SPDX-License-Identifier = "GPL-2.0-only WITH Linux-syscall-note"
