version = 1

[[annotations]]
path = ["cff.c", "cffdrivr.h", "cffgload.c", "cffgload.h", "cffload.c", "cffload.h",
        "cffobjs.c", "cffobjs.h", "cffparse.c", "cffparse.h", "cfftoken.h", "module.mk",
        "rules.mk"]
comment = "Copyright continuation line ignored by reuse for lack of word Copyright at start."
precedence = "override"
SPDX-FileCopyrightText = ["Copyright (C) 1996-2023 by David Turner, Robert Wilhelm, and Werner Lemberg."]
SPDX-License-Identifier = "FTL OR GPL-2.0-only"

[[annotations]]
path = ["cffdrivr.c"]
comment = "Copyright continuation line ignored by reuse for lack of word Copyright at start."
precedence = "override"
SPDX-FileCopyrightText = ["Copyright (C) 1996-2023 by David Turner, Robert Wilhelm, Werner Lemberg, and Dominik Röttsches."]
SPDX-License-Identifier = "FTL OR GPL-2.0-only"

[[annotations]]
path = ["cffcmap.c", "cffcmap.h", "cfferrs.h"]
comment = "Copyright continuation line ignored by reuse for lack of word Copyright at start."
precedence = "override"
SPDX-FileCopyrightText = ["Copyright (C) 2002-2023 by David Turner, Robert Wilhelm, and Werner Lemberg."]
SPDX-License-Identifier = "FTL OR GPL-2.0-only"
