version = 1

[[annotations]]
path = ["LICENSE", "extract.h"]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2005 The Android Open Source Project"
SPDX-License-Identifier = "Apache-2.0"
