/* This file was generated by syncqt. */
#ifndef QT_QTNETWORK_VERSION_H
#define QT_QTNETWORK_VERSION_H

#define QTNETWORK_VERSION_STR "6.2.11"

#define QTNETWORK_VERSION 0x06020B

#endif // QT_QTNETWORK_VERSION_H
