version = 1

[[annotations]]
path = "*"
comment = "A lot of files in this directory have no information about copyright or license. Just assuming the following."
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2013-2023 by David Turner, Robert Wilhelm, and Werner Lemberg."
SPDX-License-Identifier = "FTL OR GPL-2.0-only"

[[annotations]]
path = "afblue.pl"
comment = "Copyright continuation line ignored by reuse for lack of word Copyright at start."
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2013-2023 by David Turner, Robert Wilhelm, and Werner Lemberg."
SPDX-License-Identifier = "FTL OR GPL-2.0-only"

[[annotations]]
path = "glnames.py"
comment = "Copyright continuation line ignored by reuse for lack of word Copyright at start."
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 1996-2023 by David Turner, Robert Wilhelm, and Werner Lemberg."
SPDX-License-Identifier = "FTL OR GPL-2.0-only"

[[annotations]]
path = "update-copyright-year"
comment = "Copyright continuation line ignored by reuse for lack of word Copyright at start."
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2015-2023 by Werner Lemberg."
SPDX-License-Identifier = "FTL OR GPL-2.0-only"

[[annotations]]
path = "vms_shorten_symbol.c"
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (c) 2010, 2017 Craig A. Berry"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "ftrandom/*"
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2005, 2007, 2008, 2013 by George Williams"
SPDX-License-Identifier = "BSD-3-Clause"
