version = 1

[[annotations]]
path = ["forkfd*"]
precedence = "closest"
SPDX-FileCopyrightText = "Copyright (C) 2016 Intel Corporation Copyright (C) 2015 Klarälvdalens Datakonsult AB, a KDAB Group company, info@kdab.com"
SPDX-License-Identifier = "MIT"
